# Generated by Django 4.2.4 on 2023-08-25 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiet_dining', models.BooleanField(default=False)),
                ('enfp_meeting', models.BooleanField(default=False)),
                ('food_fighter', models.BooleanField(default=False)),
                ('news_club', models.BooleanField(default=False)),
                ('insta_vibes', models.BooleanField(default=False)),
                ('local_legend', models.BooleanField(default=False)),
                ('trending_spot', models.BooleanField(default=False)),
                ('secret_spot', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'GroupTraits',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Images')),
                ('group_traits', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Post.grouptraits')),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_posts', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='Post.post')),
            ],
        ),
    ]
