# Generated by Django 4.2.4 on 2023-08-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_traits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Post.grouptraits'),
        ),
    ]
