# Generated by Django 4.2.4 on 2023-08-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_post_group_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group_traits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.grouptraits'),
        ),
    ]
