# Generated by Django 4.2.4 on 2023-08-25 17:51

import Restaurant.models
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('taste', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Korean', 'Korean'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Western', 'Western'), ('World', 'World'), ('Buffet', 'Buffet'), ('Cafe', 'Cafe'), ('Pub', 'Pub')], default=Restaurant.models.Taste['KOREAN'], enum_class=Restaurant.models.Taste, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=200)),
                ('imageurl', models.ImageField(upload_to='images/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
            ],
        ),
    ]
