# Generated by Django 4.2.4 on 2023-08-25 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_vibes', models.BooleanField(default=False)),
                ('local_legend', models.BooleanField(default=False)),
                ('trending_spot', models.BooleanField(default=False)),
                ('secret_spot', models.BooleanField(default=False)),
                ('mint_choco', models.BooleanField(default=False)),
                ('perilla_leaves', models.BooleanField(default=False)),
                ('mara', models.BooleanField(default=False)),
                ('hawaiian_pizza', models.BooleanField(default=False)),
                ('cucumber', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
