# Generated by Django 4.2.4 on 2023-08-25 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_likes_alter_member_managers_member_spicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='member',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
